### ISSUE TITLE
Readme example error?

### ISSUE THREAD

**Issue by n9yty** [OdedShimoni/pinky-promise#1]
I could be missing something, but why in the example of the address do you revert name: to the old address, shouldn’t it be address: ?

**Comment by OdedShimoni** [comment]
Hey n9yty thanks for your question
The pinky promise from the example is setting the new address as "New Updated Address" and if it gets to the point where it has to revert (e.g. pinky promise from the same group fails), then 'revert' function is called and sets it back to "Old Address"

**Comment by n9yty** [comment]
Yes, but it sets name: not address:

**Comment by OdedShimoni** [comment]
Ohh you're right lol
